### ISSUE TITLE
`Incompatible parameter types in lambda expression` when using `satisfies`.

### ISSUE THREAD

**Issue by noel-yap** [assertj/assertj-core#1864] opened 2020-05-07 00:43 UTC
#### Summary

`Incompatible parameter types in lambda expression: expected capture of ? extends Throwable but found StatusRuntimeException` when using `satisfies`.

#### Example

```java
class StatusRuntimeException extends RuntimeException {
    …
}

…

    final Throwable thrown = catchThrowable(() -> {
        …
    });

    assertThat(thrown)
            .isInstanceOf(StatusRuntimeException.class)
            .satisfies((StatusRuntimeException sre) ->
                    assertThat(sre.getStatus().getCode())
                        .isEqualTo(Status.Code.NOT_FOUND));
```

**Comment by joel-costigliola** [comment] 2020-05-07 02:48
I could reproduce an error but not exactly yours.

I think what you are trying to do is best achieved with `isInstanceOfSatisfying`.

This test worked for me, can you try it:
```java
Throwable sre = new StatusRuntimeException();
assertThat(sre).isInstanceOf(StatusRuntimeException.class)
                // cast in the consumer block
               .satisfies(e -> assertThat(((StatusRuntimeException) e).status).isEqualTo(1));

assertThat(sre).isInstanceOfSatisfying(StatusRuntimeException.class, 
                                       e -> assertThat(e.status).isEqualTo(1));
```
with:
```java
 static class StatusRuntimeException
      extends RuntimeException
  {
    int status = 1;
  }
```

**Comment by joel-costigliola** [comment] 2020-12-28 01:32
Closing since an alternative has been given.

**Closed by joel-costigliola** 2020-12-28 01:32 UTC
