### ISSUE TITLE
StackoverflowError when usingRecursiveComparison for an Object with a nio path

### ISSUE THREAD

**Issue by rdehuyss** [assertj/assertj-core#1855] opened 2020-04-28 10:13 UTC
#### Summary
I get a StackoverflowError when usingRecursiveComparison for an Object which contains a nio path.

#### Example

```java
import org.assertj.core.api.Assertions;
import org.junit.jupiter.api.Test;

import java.nio.file.Path;
import java.nio.file.Paths;

public class AssertJBugReport {

    @Test
    public void pathThrowsStackoverflowError() {
        final Container container1 = new Container("/tmp/example");
        final Container container2 = new Container("/tmp/example");

        Assertions.assertThat(container1)
                .usingRecursiveComparison()
                .isEqualTo(container2);
    }

    public static class Container {
        private Path path;

        public Container(String path) {
            this.path = Paths.get(path);
        }

        public Path getPath() {
            return path;
        }
    }

}

```

**Comment by darkliang** [comment] 2020-04-28 10:53
I'm interested in this bug, and I'm looking into it.

**Comment by darkliang** [comment] 2020-04-28 15:40
I found the bahavior [here ](https://github.com/joel-costigliola/assertj-core/blob/df85cd3354d101b99d4264682e7bbb2fbaf2a6ad/src/main/java/org/assertj/core/api/recursive/comparison/RecursiveComparisonDifferenceCalculator.java#L137)is unexpected. `dualValuesToCompare` dose not remove `visitedDualValues`, which causes the infinite recursion. I think even though they are same objects, but refer to different addresses.

**Comment by joel-costigliola** [comment] 2020-04-28 21:39
@darkliang thanks for the investigation! 
I'm going to take care of this one as I'm fixing https://github.com/joel-costigliola/assertj-core/issues/1854 which impacts the same code and might actually fix this one too.

**Comment by joel-costigliola** [comment] 2020-04-29 09:58
@rdehuyss the issue here is that Path is an `Iterable` and the recursive comparison treats them as so instead of comparing them with Path `equals` method.

Recursively comparing `Iterable` is done by comparing elements recursively, it turns out that the first element is the `/tmp` path - also an iterable - whose first element is ... itself. boom.

the solution is to avoid treating `Path` as an `Iterable`.

**Comment by rdehuyss** [comment] 2020-04-29 10:08
Hi @joel-costigliola and @darkliang  - thanks for your swift feedback.

You say:
> the solution is to avoid treating Path as an Iterable.

I assume this is within AssertJ ?

**Comment by joel-costigliola** [comment] 2020-04-29 10:11
Yes, in AssertJ recursive comparison.

In the meantime, you can [register a specific comparator](https://assertj.github.io/doc/#assertj-core-recursive-comparison-comparators) for Path as they take precedence in the recursive comparison, or you can wait for 3.16.0 which I hope to release in a week ;-)

**Comment by darkliang** [comment] 2020-04-29 10:15
So, do we need to treat Path as an uniterable field by default? @joel-costigliola

**Comment by joel-costigliola** [comment] 2020-04-29 10:17
Yes but just for the recursive comparison.

**Comment by scordio** [comment] 2020-05-02 12:44
Abouth `Path` as iterable, we used a similar approach in `containsOnlyKeys:` https://github.com/joel-costigliola/assertj-core/blob/1b638aa55aa7bc0e9c807d9c67f4f3d6742ef630/src/main/java/org/assertj/core/api/AbstractMapAssert.java#L1152-L1161

**Comment by Brummolix** [comment] 2021-02-10 10:10
This issue is still present in 3.19.0?

**Comment by scordio** [comment] 2021-02-10 12:49
@Brummolix this should have been fixed with c5de8911ec51415fb7d20f53f5c99ee6a7fde150. Are you still facing the same issue with 3.19.0?

**Comment by Brummolix** [comment] 2021-02-10 12:59
In 3.19.0 this test (running on Windows 10) never comes to an end:

```
import static org.assertj.core.api.Assertions.assertThat;

import java.nio.file.Path;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

public class PathTest {
	private static class Bean {
		Path path;
	}

	@Test
	void test(@TempDir final Path tempDir){
		Bean bean = new Bean();
		bean.path = tempDir.resolve("file.txt");
		Bean bean2 = new Bean();
		bean2.path = tempDir.resolve("file.txt");;

		assertThat(bean)
				.usingRecursiveComparison()
				.isEqualTo(bean2);
	}
}
```

It works if I add
`.withEqualsForType((path1, path2) -> path1.equals(path2), Path.class)`

**Comment by scordio** [comment] 2021-02-14 15:04
Reopening as the issue is still present on Windows only. Created https://github.com/assertj/assertj-core/tree/investigation/gh-1855 for investigation.

**Closed** 2021-02-23 10:14 UTC
Labels: bug
