### ISSUE TITLE
Add equivalent for Hamcrest's `typeCompatibleWith`

### ISSUE THREAD

**Issue by hakanai** [assertj/assertj-core#2545] opened 2022-03-29 02:42 UTC
#### Summary

Hamcrest has an assertion `typeCompatibleWith` which is very similar to but confusingly different from AssertJ's `isAssignableFrom` in that the classes are swapped. (Blame Java for having a confusingly named method, I guess.)

While it is true that I can swap the positions of the parameters to get the right behaviour, when trying to automigrate existing code, that is less straightforward than one would hope. Also, it is still impossible to do the negated check at all, because `isNotAssignableFrom` does not exist. So it seems like the only workaround at present is a custom assertion.

It seems this was requested once before in issue #1512 but the method which was eventually added was `hasSuperclass`, which only checks the immediate superclass. Our existing implementations of this tend to check for interfaces instead.

Granted, this is stuff which is pretty rarely asserted, as _usually_ you have an object of the class and can just use `isInstanceOf` instead.

#### Example

```java
// Proposed new assertion
assertThat(ArrayList.class).isAssignableTo(Collection.class);
assertThat(ArrayList.class).isNotAssignableTo(Set.class);

// Equivalent to Hamcrest
assertThat(ArrayList.class, is(typeCompatibleWith(Collection.class)));
assertThat(ArrayList.class, is(not(typeCompatibleWith(Set.class))));
```

**Comment by joel-costigliola** [comment] 2022-03-29 03:06
I never liked `isAssignableFrom` JDK but we used it as an assertion because it was in the JDK, I suggest could have `isCompatibleWith`, ex:
```java
// class HumanJedi extends Jedi and Jedi implements UseForce
assertThat(HumanJedi.class).isCompatibleWith(Jedi.class)
                           .isCompatibleWith(UseForce.class);
assertThat(Jedi.class).isCompatibleWith(UseForce.class);
```
and the opposite with `isNotCompatibleWith`

**Comment by scordio** [comment] 2022-03-29 05:54
[`isAssignableTo(Class)`](https://truth.dev/api/latest/com/google/common/truth/ClassSubject#isAssignableTo(java.lang.Class)) was also chosen by Truth.

I still feel it'd be more familiar than `isCompatibleWith` for non Hamcrest users.

**Comment by scordio** [comment] 2022-04-15 09:02
Closing as a duplicate of #2570.

**Closed by scordio** 2022-04-15 09:02 UTC
