### ISSUE TITLE
Add more assertion on ClassAssert

### ISSUE THREAD

**Issue by onacit** [assertj/assertj-core#2570] opened 2022-04-15 04:34 UTC
#### Summary

Apologies, If I'm wrong.

It's nice that the `ClassAssert` already has an assertion for [Class#isAssignableFrom](https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html#isAssignableFrom-java.lang.Class-).
An assertion of opposite flow may be more intuitive, I believe.
Say, we have the following class or any other class being expected to implement the `MyInterface` interface.

```java
class MyClass
        extends HisClass // which extends HerClass
        implements MyInterface {
}
```

```
HerClass
    HisClass
        MyClass
```

We can,

```java
// Asserts that MyInterface.class is assignable from MyClass.class, based on Class#isAssignableFrom
assertThat(MyInterface.class)
        .isAssignableFrom(MyClass.class);
// Asserts that MyClass.class has HisClass.class as direct superclass.
assertThat(MyClass.class)
        .hasSuperclass(HisClass.class);
```

But following idiom(s) will be more intuitive.

```java
// Asserts that MyClass implements MyInterface
assertThat(MyClass.class)
        .implements(MyInterface.class)
        .isAssignableTo(MyInterface.class);
// Or
assertThat(MyClass.class)
        .implements(MyInterface.class)
        .isSubclassOf(HisClass.class) // is direct subclass; opposite of hasSuperclass(superClass)
        .isDescendentOf(HisClass.class)
        .isDescendentOf(HerClass.class) // is direct or transitively
;
assertThat(HisClass.class)
        .isAscendentOf(MyClass.class)
        .isSubclassOf(HerClass.class)
        .isDescendentOf(HerClass.class);
```

- [ ] `isAssignableTo(classOrInterface)`
- [ ] `implements(interfaceClass)`
- [ ] `isSubclassOf(superClass)` - is direct subclass of
- [ ] `is(Descendant|Descendent)Of(ascendentClass)` - is direct or transitive descendent of
- [ ] `is(Ancestor|Ascendent)Of(descendentClass)` - is direct or transitive ascendent of

**Comment by scordio** [comment] 2022-04-15 07:46
Closing as a duplicate of #2545.

I personally favor `isAssignableTo` but we haven't come to a decision yet. Feel free to propose alternative names in the other issue.

**Comment by filiphr** [comment] 2022-04-15 08:40
@scordio I do not think that this entirely a duplicate of #2545. Yes it asks for something like `isAssignableTo`. However, the other requested methods such as:

* `implements(interfaceClass)`
* `isSubclassOf(superClass)` - is direct subclass of
* `is(Descendant|Descendent)Of(ascendentClass)` - is direct or transitive descendent of
* `is(Ancestor|Ascendent)Of(descendentClass)` - is direct or transitive ascendent of

are completely unrelated to what is asked in #2545. 

In my opinion the remainder of the 4 requested new methods should be discussed in this issue. 

My opinion on the requested assertions:

* `implements(interfaceClass)` - This one is a natural to have, since there is already `hasSuperclass`. Would also be good to have the negative `doesNotImplement(interfaceClass)`
* `isSubclassOf(superClass)` - I like the idea of this one. However, I think it would be more intuitive if it was `hasParent(superClass)`
* `is(Descendant|Descendent)Of(ascendentClass)` - I think that this one could be achieved with the `isAssignableTo`. Because it tests whether the actual class can be assigned to the ascendent class. The naming might also be hard to understand for non native english speakers.
* `is(Ancestor|Ascendent)Of(descendentClass)` - Isn't this one the same as the `isAssignableFrom`? If a class is an ancestor, then it means it can be assigned from a descendent class.

**Comment by scordio** [comment] 2022-04-15 09:01
Fair point, @filiphr. Let's reopen this one and close #2545.

What I have in mind is that the idea behind `isAssignableTo` might solve most of the use cases and I'm not yet sure that the other assertions proposed by @onacit would be needed in a first round. I'd rather wait until we have concrete use cases that cannot be achieved with what the existing assertions + `isAssignableTo` would cover.

**Comment by scordio** [comment] 2022-04-15 09:05
Alternative naming proposal from https://github.com/assertj/assertj-core/issues/2545#issuecomment-1081352291 for the `isAssignableTo` assertion:
* `isCompatibleWith` / `isNotCompatibleWith`

**Comment by hakanai** [comment] 2022-04-16 07:38
`isAssignableTo` is fairly unambiguous. I have absolutely _no_ idea what `isCompatibleWith` means.

**Comment by scordio** [comment] 2022-04-17 06:41
Some additional thoughts on @filiphr's comments:

> * `implements(interfaceClass)` - This one is a natural to have, since there is already `hasSuperclass`. Would also be good to have the negative `doesNotImplement(interfaceClass)`

`hasSuperclass` was a straightfoward addition because in line with [`getSuperclass`](https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html#getSuperclass--) from the JDK. However, it looks only one level up and this might not be crystal-clear from the assertion name.

If we would like to add `implements`, I imagine this should check recursively if an interface is there. Assuming `isAssignableTo` is available, wouldn't the following do the same?

```java
assertThat(ArrayList.class).isAssignableTo(Collection.class);
```

> * `isSubclassOf(superClass)` - I like the idea of this one. However, I think it would be more intuitive if it was `hasParent(superClass)`

Isn't this also the same as `isAssignableTo`?

> * `is(Descendant|Descendent)Of(ascendentClass)` - I think that this one could be achieved with the `isAssignableTo`. Because it tests whether the actual class can be assigned to the ascendent class. The naming might also be hard to understand for non native english speakers.

I would also favor `isAssignableTo`.

> * `is(Ancestor|Ascendent)Of(descendentClass)` - Isn't this one the same as the `isAssignableFrom`? If a class is an ancestor, then it means it can be assigned from a descendent class.

I also see it covered by `isAssignableFrom`. However, assuming `isAssignableTo` is added, I'd evaluate the deprecation of `isAssignableFrom` which is on average the source of confusion and could be achieved with `isAssignableTo` with inverted parameters.

**Comment by onacit** [comment] 2022-04-20 12:22
> I also see it covered by isAssignableFrom. However, assuming isAssignableTo is added, I'd evaluate the deprecation of isAssignableFrom which is on average the source of confusion and could be achieved with isAssignableTo with inverted parameters.

I think the `isAssignableFrom` has its own responsibility as it is.

```java
class A { }
class B extends A { }
class C extends B {}

assertThat(B.class)
        .isAssignableTo(A.class)
        .isAssignableFrom(C.class)
;
```

**Comment by nith2001** [comment] 2022-05-03 21:57
Hello @scordio, @jessicant and myself are interested in this issue, but we're a but lost on what the deliverables are and what specifically needs to be accomplished and how, since it sounds like there's some debate on which methods out of the 5 proposed are needed/not needed. 

Is the function `isAssignableTo(classOrInterface)` the one to implement?

**Comment by joel-costigliola** [comment] 2022-05-04 10:29
I think `isAssignableTo` is a good choice as it is quite clear.

**Comment by scordio** [comment] 2022-05-04 10:35
**Team decision**: let's add only `isAssignableTo(Class<?>)` to `AbstractClassAssert`.

**Comment by nith2001** [comment] 2022-05-10 21:28
@scordio Here's what we've come up with under `Classes.java`:

```
  public void assertIsAssignableTo(AssertionInfo info, Class<?> actual, Class<?> other) {
    assertNotNull(info, actual);
    assertNotNull(info, other);
    classParameterIsNotNull(other);
    if (!other.isAssignableFrom(actual))
      throw failures.failure(info, shouldBeAssignableTo(actual, other));
  }
```
We've made another ErrorMessageFactory as a result. Still undergoing testing, but any thoughts on the code? Should we code any other functions like `implements()` or `isSubclassOf(Class<?>)` etc?

**Comment by onacit** [comment] 2022-05-11 02:58
@nith2001 isAssignableTo should be enough for this issue.

**Comment by jessicant** [comment] 2022-05-11 03:14
Oh okay, that is alright. We attend the same university and are working closely on this issue together is why I ask. It would just be simpler for me to see this issue on my assigned page, but whatever works :)

**Comment by jessicant** [comment] 2022-05-11 03:18
I am working closely with @nith2001 on this issue. As such, would someone please assign me as well?

**Comment by onacit** [comment] 2022-05-11 03:18
@jessicant It's 8 PM there in Seattle, WA. Aren't you supposed to enjoy beer or Netflix with your friends? Sorry, kidding. :)

**Comment by scordio** [comment] 2022-05-27 09:04
From https://github.com/assertj/assertj-core/issues/1512#issuecomment-1139412673:

> (Also, adding negation forms for both the existing one - `isNotAssignableFrom` - and the suggested new method - `isNotAssignableTo` - would be incredibly useful. Right now, I'm doing a workaround on the form `assertThat( ParentClass.class ).matches( cls -> !cls.isAssignableFrom( ChildClass.class ) ))`, but it's a bit rough. 🙂)

**Comment by nith2001** [comment] 2022-05-27 16:23
Would you like us to implement `isNotAssignableTo` after we get our isAssignableTo code checked out?

**Comment by scordio** [comment] 2022-05-27 16:24
@nith2001 for now, let's stay with `isAssignableTo` only and we'll come back to the next steps later.

**Comment by nith2001** [comment] 2022-05-27 16:46
@scordio Ok, I believe we've finished out initial implementation for `isAssignableTo`.

**Comment by nith2001** [comment] 2022-05-27 22:21
PR: https://github.com/assertj/assertj-core/pull/2611

**Closed** 2022-07-09 09:19 UTC

**Comment by scordio** [comment] 2022-07-09 09:25
@perlun do you think `isAssignableTo` and `isAssignableFrom` are enough to cover your use cases?

If not, could you please provide an example?

**Comment by perlun** [comment] 2022-11-16 18:31
@scordio Sorry for the late call, but yes, I think `isAssignableTo` and `isAssignableFrom` are good enough for now. :+1: 

`isSubclassOf`/`hasParent` are quite interesting (but not directly required by me). I think they are unpleasantly "less precise" though; they first one would perhaps more rightfully be `isDirectSubclassOf` since in an `A -> B -> C`, `C` is by definition a subclass of `A` _as well_ as of `B`. `hasParent` is perhaps less unambiguous in this since parents and grandparents are conceptually different. :slightly_smiling_face:
