### ISSUE TITLE
How do I force extracting from private value instead of from getters?

### ISSUE THREAD

**Issue by EgMan** [assertj/assertj-core#1389] opened 2019-01-07 23:16 UTC
I'm running into an issue where a class of mine returns an Optional of its private fields, but the fields themselves are not wrapped in optionals.  I'm trying to recursively compare field by field, but since Optional overrides its isEqual, it will fail every time it encounters a field because the object references are different.  It seems I can either wait for #1002 to have access to forcingRecursiveComparisonFor (not possible due to time constraint), or force the utility to compare with the non-optional private fields.  

The below example isn't the actual code, but a simulation of what exactly is happening
```java
public class A 
{
    private B b;
    //setter for b
    public Optional<B> getB()
    {
        return Optional.ofNullable(b);
    }
}
```
Assume class B has nested private variables exposed with a public getter that wraps it as an optional as well.  

I wish to do something like this:
```
A a1 = returnAnInstanceOfA();
A a2 = returnADifferentInstanceOfA();

assertThat(a1).isEqualToComparingFieldByFieldRecursively(a2);
```
But even if each of the primitive fields are the same, I'll get something like this:
```
Path to difference: <A>
- actual : <Optional[A@ab4d2ba]]>
- expected: <Optional[A@2aa0feb2]>
```

So, I figure I can either get the custom comparator to work so Optionals will actually be recursively asserted on (I've had no luck with this so far), or I could force assertJ to extract from the private fields instead of trying to use the getters.  

Any help would be greatly appreciated.  Thank you.

**Comment by joel-costigliola** [comment] 2019-01-08 09:53
There is no way at the moment to choose field over property unfortunately.

I haven't tried it but it would be worth giving a try to create a generic `OptionalComparator` that compares their content field by field with `FieldByFieldComparator` (or something alike) and register it with `usingComparatorForType`.

#1002 will indeed allow you to ignore overridden equals method and compare field by field.

Hope it helps.

**Comment by EgMan** [comment] 2019-01-08 15:32
I have tried to do something like that, but I need to do it recursively.  I'm having trouble finding documentation on how to properly construct the recursive field by field comparator.  I've tried 
```
TypeComparators typeComparators = new TypeComparators();
RecursiveFieldByFieldComparator recursiveCompair = 
        new RecursiveFieldByFieldComparator(Collections.emptyMap(), TypeComparators.defaultTypeComparators());

assertThat(actualCriteria)
    .usingComparatorForType(recursiveCompair, Optional.class)
    .isEqualToComparingFieldByFieldRecursively(expectedCriteria);
```

But I've had no luck.  Do you have any insight into what I'm doing wrong?

**Comment by EgMan** [comment] 2019-01-08 17:55
disregard my approach above, I was able to create a custom comparator to accomplish this, but the assertion message generated from within isEqualToComparingFieldByFieldRecursively still remains the same.  

In other words, it is now correctly checking field by field, but when a nested field is different, there is no specific error message to help debug, there is only 'optional is different than optional.'  I don't suppose there is a way to make this assertion message reflect what is actually compared using the custom comparator. Is there?
```
Comparator<Object> OptionalComp = new Comparator<Object>() {

    @SuppressWarnings("unchecked")
    @Override
    public int compare(Object expected, Object actual)
    {
        if (expected instanceof Optional) {
            expected = ((Optional<Object>) expected).get();
            actual = ((Optional<Object>) actual).get();
        }
        
        RecursiveFieldByFieldComparator recursiveCompair = 
                new RecursiveFieldByFieldComparator(Collections.emptyMap(), TypeComparators.defaultTypeComparators());
        
        return recursiveCompair.compare(actual, expected);
        
    }
};
```

**Comment by joel-costigliola** [comment] 2019-01-08 21:23
I don't think there is a way to get the optional internal comparison differences, once the custom Optional comparator returns this ends the recursive comparison for the optional fields (as it would for any other fields compared with a custom comparator).

Since there is no easy way around that, you will have to wait for #1002 to be available, hopefully I'm currently working on it, I have put some checklist to show my progress if you are interested, there is hope! ;-)

**Comment by joel-costigliola** [comment] 2019-03-03 10:08
Ok this one did not make the cut for the first version of the new recursive comparison api but I'm planning it for the next release, it is also I believe a duplicate of https://github.com/joel-costigliola/assertj-core/issues/1424, @EgMan could you confirm this last point.

**Comment by EgMan** [comment] 2019-03-04 16:20
That is correct, it does look like mostly the same issue.  
The only difference is that in addition to updating the recursive API so that you can force recursive assertion despite overridden equals, my problem could also be addressed by updating the recursive API so that you can force extraction from private values instead of through getters.

**Comment by joel-costigliola** [comment] 2019-03-04 20:40
I think it makes more sense to support `Optional` than to favor private fields over getters, it would be a non obvious behavior (even if you can configure it you might just want to use that for fields exposed with getter returning Optional).

**Comment by joel-costigliola** [comment] 2020-12-29 10:25
#1424  is done

**Closed by joel-costigliola** 2020-12-29 10:25 UTC
