### ISSUE TITLE
Don't use reflection to compare AtomicReference in the recursive comparison 

### ISSUE THREAD

**Issue by joel-costigliola** [assertj/assertj-core#2466] opened 2022-01-12 20:41 UTC
#### Summary

Don't use reflection to compare AtomicReference in the recursive comparison as it fails in java 17.
https://stackoverflow.com/questions/70670884/assertj-issue-with-assertions-assertthat-usingrecursivecomparison-ignoringf/70688101#70688101

**Comment by WojciechZankowski** [comment] 2022-01-15 23:32
That's actually a duplicate of that issue: https://github.com/assertj/assertj-core/issues/2450 with the different output because of used Java version. It happens as well with other classes placed inside of ```java.util.concurrent.atomic.*``` or ```java.util.concurrent.locks.*```

I believe it would be good to find a generic solution to that issue as it can happen not only with JDK classes, right?

**Closed** 2022-02-22 09:35 UTC
Labels: bug, recursive comparison, Java 17+
