### ISSUE TITLE
The `url` value in pom.xml is not getting resolved.

### ISSUE THREAD

**Issue by nstdio** [assertj/assertj-core#2708] opened 2022-07-15 18:25 UTC
#### Summary
As you can see from [assertj-core-3.23.1.pom](https://repo1.maven.org/maven2/org/assertj/assertj-core/3.23.1/assertj-core-3.23.1.pom) the project url is treated as literal.

**Comment by Giovds** [comment] 2022-07-15 22:10
I believe this is expected behavior, since you upload your POM as it to Maven central. You can validate this by looking at the [POM from maven](https://repo1.maven.org/maven2/org/apache/maven/maven/3.8.6/maven-3.8.6.pom) itself for example where the URL isn't interpolated yet either.

The expressions are interpolated once you start building the effective-pom in memory. You can validate this when you run `mvn help:effective-pom` for example. It does however not resolve `${project.parent.url}` so was either never supported or doesn't seem to work anymore? I'd have to look into that.

I get the following output when I run it with a Maven 4 snapshot build and the same for Maven 3.8.6:
```text
 <artifactId>assertj-core</artifactId>
  <version>3.24.0-SNAPSHOT</version>
  <name>AssertJ fluent assertions</name>
  <description>Rich and fluent assertions for testing for Java</description>
  <url>${project.parent.url}#assertj-core</url>
  <organization>
    <name>AssertJ</name>
    <url>https://assertj.github.io/doc/</url>
  </organization>
```

**Comment by Giovds** [comment] 2022-07-15 22:24
As an alternative we could change it to `${project.organization.url}` since that is inherited from the parent, and is accessible from the child POM. Once you run `mvn help:effective-pom` with this change it will be interpolated to:
```text
<url>https://assertj.github.io/doc/#assertj-core</url>
```

**Comment by scordio** [comment] 2022-07-15 23:09
Nice catch, @nstdio! Fixed with @Giovds' proposal.

Thanks!

**Closed** 2022-07-15 23:08 UTC
