### ISSUE TITLE
withFailMessage() crashes when its input contains % sign

### ISSUE THREAD

**Issue by Eru-gg** [assertj/assertj-core#2556] opened 2022-04-02 16:20 UTC
#### Summary
Real life example: I'm testing correctness of auto-generated urls. Some of those URLs contains % signs, because of [http escaping](https://www.w3schools.com/tags/ref_urlencode.asp). If I try to use `assertThat().withFailMessage().isEqualTo()`, then I'm getting an an exception from `String.format()` because Java gets confused about the percent signs

#### Example

```java
assertThat(1).withFailMessage("because %2B reasons").isEqualTo(2)
```

**Comment by joel-costigliola** [comment] 2022-04-03 09:47
Thanks for reporting this @Eru-gg, the reason is that `withFailMessage(String newErrorMessage, Object... args)` is interpreted as `String.format`, we will add `withFailMessage(String newErrorMessage)` that just take the message as is.

**Comment by scordio** [comment] 2022-05-07 00:21
@Eru-gg we cannot reproduce the issue with the latest version so I close this issue, but happy to reopen it in case you can provide a reproducible example.

**Closed by scordio** 2022-05-07 00:21 UTC
