### ISSUE TITLE
Introspection.findGetter find wrong getter method with return type void

### ISSUE THREAD

**Issue by weissreto** [assertj/assertj-core#2068] opened 2020-12-10 15:39 UTC
#### Summary
Introspection does not work if target class has a method that has same name as the field I like to extract but with return type void

#### Example
```java
org.apache.xerces.dom.events.EventImpl event = ...
assertThat(event)
        .extracting("preventDefault")
        .asInstanceOf(InstanceOfAssertFactories.BOOLEAN)
        .isTrue();
```
The class EventImpl has a method 
```java
public void preventDefault()
```
The method findGetter of class org.assertj.core.util.introspection.Introspection will return this method as getter. Therefore, the field is not introspected at all. The found getter method will return null since it has void as return type.

To fix this the method isValidGetter should check if the given method has a return type that is not void.

#### Workaround
Introspection.setExtractBareNamePropertyMethods(false);

**Comment by joel-costigliola** [comment] 2020-12-10 20:24
Thanks for reporting this, the workaround mentioned is the default behavior since 3.18.0.

**Comment by weissreto** [comment] 2020-12-11 06:54
Thanks for this information. I'm using 3.17.0.

**Comment by scordio** [comment] 2020-12-11 08:41
@weissreto is upgrading from 3.17.0 to 3.18.1 an option for you? If so, I would close this issue.

**Comment by weissreto** [comment] 2020-12-11 08:47
Hi @scordio 
Yes I can update no problem. 
But I think the same problem can also occur if you have a method called getXYZ with void as return type. If you then want to introspect the xyz field you get the same error and the workaround does not fit then. 
I know this is a strange use case. If you wish I can provide a PR with a fix.

**Comment by scordio** [comment] 2020-12-11 09:02
Fair point, we should look into it and add a test case for regression, so it is better to keep this issue open.

A PR would be great if you have time. Thanks!

**Closed** 2020-12-13 07:30 UTC
